name: CI Job
on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: A job to run in docker container
    steps:
      - name: Run action step
        uses: actions/checkout@v2

      - name: Run test and save coverage profile
        run: go test -race -v -cover -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt