name: Test and coverage
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: A job to run in docker container
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Gather dependencies
        run: go mod download

      - name: Run coverage
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            go test -v -cover -coverprofile=coverage.txt -covermode=atomic ./...
          else
            go test -v -cover -race -coverprofile=coverage.txt -covermode=atomic ./...
          fi

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}